config/routes.rb
#require 'sidekiq/web'
Rails.application.routes.draw do
  
  resources :facilities do
  	collection do
      post 'search'
    end
  end
  
  root to: "home#index"
  
  devise_for :users
 
  resources :rooms, controller: 'admin/rooms'
  resources :bookings
  
  #mount Sidekiq::Web, at: '/sidekiq'
end

app/models/room.rb
class Room < ActiveRecord::Base
	resourcify
	attr_accessor :facilities_fields
	
	has_many :bookings, dependent: :destroy
	has_and_belongs_to_many :facilities
	accepts_nested_attributes_for :facilities
	
	after_save :create_facilities
  
  validates :room_no, :title, presence: true

	def create_facilities
		if self.facilities_fields
		  self.facilities.delete_all
		  facilitites = Facility.where(id: self.facilities_fields[:id])
		  self.facilities << facilitites
		end
	end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :facility_ids, only: [:new, :edit, :create, :update]

  def index
    params[:page] = 1 if params[:page].blank?
    @rooms = Room.page(params[:page]).per(20)
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
    @room_facility_ids = @room.facilities.pluck(:id)
  end

  def create
    @room = Room.create(room_params)
    return render :new  if @room.errors.present?
    redirect_to rooms_path, notice: 'room was successfully created.'
  end

  def update
    return render :edit if not @room.update(room_params)
    redirect_to rooms_path, notice: 'room was successfully updated.'
  end

  def destroy
    @room.destroy
    redirect_to rooms_path, notice: 'room was successfully destroyed.'
  end

  private

    def facility_ids
      @facilities = Facility.select(:id, :title)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit!
    end
end

app/helpers/admin/room_helper.rb
module Admin::RoomHelper
end

app/views/admin/rooms/_form.html.haml
= form_for(@room) do |f|
  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-text-input"} Title
    .col-xs-6
      = f.text_field :title, class: "form-control"
  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-search-input"} Room No.
    .col-xs-6
      = f.text_field :room_no, class: "form-control"

  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-search-input"} Facilities
    .col-xs-6
      - @facilities.each do |ff|
        = check_box_tag "room[facilities_fields][id][]", ff.id, (@room_facility_ids.include?(ff.id) if @room_facility_ids.present?)
        = ff.title
      
  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-text-input"}
    .col-xs-10
      = f.submit "Submit", class: "btn btn-default"
%br/

app/views/admin/rooms/edit.html.haml
.col-md-12
  .col-md-2
  .col-md-10
    %h4 Edit #{@room.title}
  = render 'form'

app/views/admin/rooms/index.html.haml
.btn-group-vertical.pull-left
  %h4 List Of Rooms
- if can? :new, Room
  = link_to "New Room", new_room_path, class: "btn btn-default pull-right"

%table.table.table-bordered
  %thead
    %tr
      %th{:scope => "row"} #
      %th{:scope => "row"} Title
      %th{:scope => "row"} Room No.
      %th{:scope => "row"} Facilities
      - if (can? :edit, Room) || (can? :destroy, Room)
        %th{:scope => "row", :colspan => "2"} Action
  %tbody
    - @rooms.each_with_index do |room, index|
      %tr
        %td= index + 1 
        %td= room.title
        %td= room.room_no
        %td= room.facilities.pluck(:title).join(', ')
        - if can? :edit, room
          %td= link_to 'Edit', edit_room_path(room)
        - if can? :destroy, room
          %td= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }
  
= paginate @rooms

app/views/admin/rooms/new.html.haml
.col-md-12
  .col-md-2
  .col-md-10
    %h4 New Room
  = render 'form'