config/routes.rb
#require 'sidekiq/web'
Rails.application.routes.draw do
  
  resources :facilities do
  	collection do
      post 'search'
    end
  end
  
  root to: "home#index"
  
  devise_for :users
 
  resources :rooms, controller: 'admin/rooms'
  resources :bookings
  
  #mount Sidekiq::Web, at: '/sidekiq'
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  
  after_initialize :init

  # after_save :check_status
  before_save :check_status

  validates :start_date, :end_date, presence: true
  
  default_scope -> { where.not(status: CANCEL) }
  
  def init
    self.status ||= ALLOTED
  end

  def check_status
    case self.status
    when ALLOTED, WAITING
      if datetime_slot_available?
        self.room.update_column('status', ALLOTED) if self.room.status != ALLOTED
        self.status = ALLOTED
        UserMailer.booking_confirmation(self.user, self).deliver
      elsif
        self.status = WAITING
        UserMailer.waiting_rooms(self.user, self).deliver
      end
    when CANCEL
      free_room_for_booking
    else
    end
  end

  def free_room_for_booking
    self.room.update_column('status', FREE)
    upcomming_booking = upcomming_bookings.first
    UserMailer.booking_cancellation(self.user, self).deliver
    if upcomming_booking
      upcomming_booking.booking_confirmation_mail
      upcomming_booking.update_column('status', ALLOTED)
      upcomming_booking.room.update_column('status', ALLOTED)
      UserMailer.booking_confirmation(upcomming_booking.user, upcomming_booking).deliver
    end
  end
  
  def upcomming_bookings
    Booking.where(room_id: self.room_id, status: [WAITING]).where.not(id: self.id).order("start_date ASC")
  end

  def datetime_slot_available?
    # not Booking.where(room_id: self.room_id, status: [ALLOTED, WAITING], start_date: self.start_date..self.end_date).where.not(id: self.id).present?
    not Booking.where(room_id: self.room_id, status: [ALLOTED, WAITING]).where(' start_date >= ?', self.start_date.to_formatted_s(:db)).where.not(id: self.id).present?
  end

  def self.close_bookings
    bookings = Booking.where(status: [ALLOTED, WAITING]).where("end_date <= ?", Time.now.to_formatted_s(:db))
    bookings.update_all(status: CANCEL)
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :verify_room, only: [:create, :update]
  before_action :rooms_list, only: [:new, :edit, :create, :update]
  # GET /bookings
  # GET /bookings.json
  def index
    params[:page] = 1 if params[:page].blank?
    @bookings = Booking.page(params[:page]).per(50)
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = current_user.bookings.create(booking_params)
    return render :new  if @booking.errors.present?
    redirect_to bookings_path, notice: 'Booking was successfully created.'
  end

  def update
    return render :edit unless @booking.update_attributes(booking_params)
    redirect_to bookings_path, notice: 'Booking was successfully updated.'
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, notice: 'Booking was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = current_user.bookings.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:room_id, :start_date, :end_date, :status)
    end

    def verify_room
      #redirect_to new_booking_path, warning: 'Room does not exist.' unless Room.find_by_id(booking_params[:room_id])
    end

    def rooms_list
      @rooms = Room.all.select(:id, :title, :room_no)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.haml
/ = form_for(@booking) do |f|
/   .form-group.row
/     %label.col-xs-2.col-form-label{:for => "example-text-input"} Select Room
/     .col-xs-6
/       = f.select :room_id, options_from_collection_for_select(@rooms, "id", "room_no", f.object.room_id), class: "form-control"
/   .form-group.row
/     %label.col-xs-2.col-form-label{:for => "example-text-input"} Start datetime
/     .col-xs-6
/       = f.text_field :start_date, class: "form-control datetimepicker", value: (f.object.start_date.strftime("%d-%m-%Y %H:%M:%S") if f.object.start_date)
/   .form-group.row
/     %label.col-xs-2.col-form-label{:for => "example-search-input"} End datetime
/     .col-xs-6
/       = f.text_field :end_date, class: "form-control datetimepicker", value: (f.object.end_date.strftime("%d-%m-%Y %H:%M:%S") if f.object.end_date)
 
/   .form-group.row
/     %label.col-xs-2.col-form-label{:for => "example-text-input"}
/     .col-xs-10
/       = f.submit "Submit", class: "btn btn-default"
/ %br/


= form_tag(search_facilities_path, remote: true, method: 'post', id:'search_form') do
  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-text-input"} Search Rooms by facilities
    .col-xs-5.p-l-0
      .input-group.search
        %span.input-group-btn
          %button#btn-height.btn.btn-default{:style => "height: 35px;", :type => "button"}
            %i.glyphicon.glyphicon-search
        = text_field_tag :search_keyword, nil, placeholder: 'search for...', class: 'form-control'
= form_for(@booking) do |f|
  .form-group.row
    .search_result
  / .form-group.row
  /   %label.col-xs-2.col-form-label{:for => "example-text-input"} Search Rooms by facilities
  /   .col-xs-6
  /     = search_field_tag 'name',"", class: "form-control",remote:true
  - if f.object.room
    .form-group.row
      .br
      %label.col-xs-2.col-form-label{:for => "example-text-input"} Booked Room
      .col-xs-6
        = f.object.room.room_no
        =# f.select :room_id, options_from_collection_for_select(@rooms, "id", "room_no", f.object.room_id), class: "form-control"
  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-text-input"} Start datetime
    .col-xs-6
      = f.text_field :start_date, class: "form-control datetimepicker", value: (f.object.start_date.strftime("%d-%m-%Y %H:%M:%S") if f.object.start_date)
  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-search-input"} End datetime
    .col-xs-6
      = f.text_field :end_date, class: "form-control datetimepicker", value: (f.object.end_date.strftime("%d-%m-%Y %H:%M:%S") if f.object.end_date)

  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-text-input"}
    .col-xs-10
      = f.submit "Submit", class: "btn btn-default"
%br/

app/views/bookings/edit.html.haml
.col-md-12
  .col-md-2
  .col-md-10
    %h4 Edit Booking
  = render 'form'

app/views/bookings/index.html.haml
.btn-group-vertical.pull-left
  %h4 Listing Bookings
- if can? :new, Booking
  = link_to "New Booking", new_booking_path, class: "btn btn-default pull-right"

%table.table.table-bordered
  %thead
    %tr
      %th{:scope => "row"} #
      %th{:scope => "row"} User Name
      %th{:scope => "row"} Room No.
      %th{:scope => "row"} Start datetime
      %th{:scope => "row"} End datetime
      %th{:scope => "row"} Status
      - if (can? :edit, Room) || (can? :destroy, Room)
        %th{:scope => "row", :colspan => "4"} Action
  %tbody
    - @bookings.each_with_index do |booking, index|
      %tr
        %td= index + 1 
        %td= booking.user.full_name
        %td= booking.room.room_no
        %td= date_format(booking.start_date)
        %td= date_format(booking.end_date)
        %td= booking.status
        - if (can? :cancel, booking) && current_user.id == booking.user.id
          %td= button_to "Cancel", booking_path(id: booking.id, booking: {status: CANCEL, room_id: booking.room_id}), method: :put
        - if (can? :edit, booking) && current_user.id == booking.user.id
          %td= link_to 'Edit', edit_booking_path(booking)
        - if (can? :delete, booking) && current_user.id == booking.user.id
          %td= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }

= paginate @bookings

app/views/bookings/new.html.haml
.col-md-12
  .col-md-2
  .col-md-10
    %h4 New Booking
  = render 'form'