config/routes.rb
#require 'sidekiq/web'
Rails.application.routes.draw do
  
  resources :facilities do
  	collection do
      post 'search'
    end
  end
  
  root to: "home#index"
  
  devise_for :users
 
  resources :rooms, controller: 'admin/rooms'
  resources :bookings
  
  #mount Sidekiq::Web, at: '/sidekiq'
end

app/models/facility.rb
class Facility < ActiveRecord::Base
	has_and_belongs_to_many :rooms
	accepts_nested_attributes_for :rooms
    
  def self.search(params)
    unless params[:search_keyword].blank?
      #Facility.where("title ilike '%#{params[:search_keyword].strip}%'")
      Room.joins(:facilities).where("facilities.title ilike '%#{params[:search_keyword].strip}%'")
    end
  end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: [:show, :edit, :update, :destroy]

  def index
    params[:page] = 1 if params[:page].blank?
    @facilities = Facility.page(params[:page]).per(20)
  end

  def show
  end

  def new
    @facility = Facility.new
  end

  def edit
  end

  def create
    @facility = Facility.create(facility_params)
    return render :new  if @facility.errors.present?
    redirect_to facilities_path, notice: 'room was successfully created.'
  end

  def update
    return render :edit if not @facility.update(facility_params)
    redirect_to facilities_path, notice: 'room was successfully updated.'
  end

  def destroy
    @facility.destroy
    redirect_to facilities_path, notice: 'room was successfully destroyed.'
  end

  def search
    @search_result = Facility.search(params)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facility
      @facility = Facility.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facility_params
      params.require(:facility).permit(:title, :desctription)
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_facilities_search.html.haml
.col-sm-12
  .col-sm-4
  .col-sm-4
    -unless @search_result.blank?
      -@search_result.each do |res|
        = radio_button_tag "booking[room_id]", res.id#, (@room_facility_ids.include?(ff.id) if @room_facility_ids.present?)
        =res.title
        =res.room_no
        .br

app/views/facilities/_form.html.haml
= form_for(@facility) do |f|
  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-text-input"} Title
    .col-xs-6
      = f.text_field :title, class: "form-control"
  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-search-input"} Desctription
    .col-xs-6
      = f.text_area :desctription, class: "form-control"      
  .form-group.row
    %label.col-xs-2.col-form-label{:for => "example-text-input"}
    .col-xs-10
      = f.submit "Submit", class: "btn btn-default"
%br/

app/views/facilities/edit.html.haml
.col-md-12
  .col-md-2
  .col-md-10
    %h4 Edit #{@facility.title}
  = render 'form'

app/views/facilities/index.html.haml
.btn-group-vertical.pull-left
  %h4 List Of Facilities
- if can? :new, Facility
  = link_to "New Facility", new_facility_path, class: "btn btn-default pull-right"

%table.table.table-bordered
  %thead
    %tr
      %th{:scope => "row"} #
      %th{:scope => "row"} Title
      %th{:scope => "row"} Desctription
      - if (can? :edit, Facility) || (can? :destroy, Facility)
        %th{:scope => "row", :colspan => "4"} Action
  %tbody
    - @facilities.each_with_index do |facility, index|
      %tr
        %td= index + 1 
        %td= facility.title
        %td= facility.desctription
        - if can? :edit, facility
          %td= link_to 'Edit', edit_facility_path(facility)
        - if can? :delete, facility
          %td= link_to 'Destroy', facility, method: :delete, data: { confirm: 'Are you sure?' }
= paginate @facilities

app/views/facilities/new.html.haml
.col-md-12
  .col-md-2
  .col-md-10
    %h4 New Facility
  = render 'form'

app/views/facilities/search.js.haml
$(".search_result").html("#{escape_javascript(render partial: 'facilities_search')}");