config/routes.rb
#require 'sidekiq/web'
Rails.application.routes.draw do
  
  resources :facilities do
  	collection do
      post 'search'
    end
  end
  
  root to: "home#index"
  
  devise_for :users
 
  resources :rooms, controller: 'admin/rooms'
  resources :bookings
  
  #mount Sidekiq::Web, at: '/sidekiq'
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#myNavbar", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} Room Booking
    #myNavbar.collapse.navbar-collapse
      - if current_user
        %ul.nav.navbar-nav
          %li{class: "#{params[:controller] == 'home' ? 'active' : '' }" }
            = link_to "Home", root_path
          %li{class: "#{params[:controller] == 'admin/rooms' ? 'active' : '' }" }
            =link_to 'Room', rooms_path
          %li{class: "#{params[:controller] == 'bookings' ? 'active' : '' }" }
            =link_to 'Booking', bookings_path
          %li{class: "#{params[:controller] == 'facilities' ? 'active' : '' }" }
            =link_to 'facilities', facilities_path
        
        %ul.nav.navbar-nav.navbar-right
          %li
            %a.navbar-brand{:href => "#"}
              = current_user.email rescue nil
          %li
            =link_to destroy_user_session_path, :method => :delete do 
              %span.glyphicon.glyphicon-log-in
              Sign out

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ConferenceRoomBooking
    = stylesheet_link_tag    'application'#, media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application'#, 'data-turbolinks-track' => true
    

    = csrf_meta_tags
  %body.body
    = render partial: 'layouts/header'
    .col-md-12
      - if notice.present?
        .alert.alert-success
          %strong Success :
          = notice
      - if warning.present?
        .alert.alert-warning
          %strong Warning :
          = warning
    .container
      %section.row
        = yield
  :javascript
    $('.alert').delay(5000).fadeOut('slow');